### ISSUE TITLE
Categorization support

### ISSUE THREAD

**Issue by Zero3K** [Zero3K/nulinks#1]
It would be nice if it supported the categorization of uploaded/posted files and offer a page that lists the categories. Clicking on one would then show the files that have been given the mentioned category.

**Comment by SahilAgarwal321** [comment]
Examples? What categories exist?? Are they predefined?

**Comment by Zero3K** [comment]
Audio, Video, Applications, Games, Porn, Other (those are the ones that The Pirate Bay uses).

**Comment by Zero3K** [comment]
Any news?

**Comment by SahilAgarwal321** [comment]
Not yet. This will need changes in DB. @TheDurtch  can you do a migrate on the server?? I'll push changes in a while.

**Comment by Zero3K** [comment]
Oh, okay.

**Comment by SahilAgarwal321** [comment]
Once you have made changes to DB, you will need to add these categories to DB via admin panel.

**Comment by Zero3K** [comment]
I think that the Category column should be before the Name column.

**Comment by SahilAgarwal321** [comment]
Done. Closing this.
