### ISSUE TITLE
Add link to Fopnu's site in the footer

### ISSUE THREAD

**Issue by Zero3K** [Zero3K/nulinks#12]
Fopnu's site (which is https://www.fopnu.com) should be added to the footer so people can use the links on the site.

**Comment by SahilAgarwal321** [comment]
Can you tell me what the text should be exactly? I'll add that.

**Comment by SahilAgarwal321** [comment]
@Zero3K ?

**Comment by Zero3K** [comment]
These links are powered by the Fopnu P2P Network - https://www.fopnu.com
