### ISSUE TITLE
Suggestion regarding the Search Box

### ISSUE THREAD

**Issue by Zero3K** [Zero3K/nulinks#14]
It should be placed in the top header next to the Home, etc. links with the text used in it stating "Search...".

**Comment by SahilAgarwal321** [comment]
Not possible as the search bar is essentially a part of the table (due to the datatables library that I am using for this). Placing it in the header bar will break stuff later on.

**Comment by Zero3K** [comment]
Then how can it be made nicer looking?

**Comment by Zero3K** [comment]
Can you at least center it, remove the Search: next to it and add Search... into it?

**Comment by SahilAgarwal321** [comment]
I'll see.

**Comment by Zero3K** [comment]
Also, when categorization is supported, there should be a drop down box added next to the Search Box that shows the categories so a user can search for links that have the mentioned category applied to them.

**Comment by SahilAgarwal321** [comment]
Let's create a different issue for that later. Not a part of this issue.

**Comment by Zero3K** [comment]
Okay.
