### ISSUE TITLE
Add the text mentioning the Bitcoin address back to the footer

### ISSUE THREAD

**Issue by Zero3K** [Zero3K/nulinks#16]
Please do that so people can donate to the admin of the server if they feel like it.

**Comment by Zero3K** [comment]
The text is as follows:

Bitcoin Wallet Address (for donations in order to keep this site running): 14CR1LskZ8gCpJNcx3HCMXtwW6NEvS1nBj

**Comment by SahilAgarwal321** [comment]
Done.
