### ISSUE TITLE
Update the Nulinks version mentioned in the footer

### ISSUE THREAD

**Issue by Zero3K** [Zero3K/nulinks#17]
Please update the version of it that is mentioned since it has improved beyond that version.

**Comment by SahilAgarwal321** [comment]
Will update to 0.2

**Comment by Zero3K** [comment]
Why not 0.5?

**Comment by SahilAgarwal321** [comment]
It was 0.1 before. So the next should be 0.2 right? Why 0.5?

**Comment by Zero3K** [comment]
Because of all the changes that you did to it.

**Comment by TheDurtch** [comment]
0.2 is fine
