### ISSUE TITLE
Rename unchainedTorrent to Nulinks

### ISSUE THREAD

**Issue by Zero3K** [Zero3K/nulinks#19]
The code that mentions unchainedTorrent should be made to mention Nulinks. Also, the folder with that name should be renamed to Nulinks.

**Comment by SahilAgarwal321** [comment]
That can't be done very easily. I'll see if it can be done but will probably break the code.  I dont think its a big thing so we should ignore it.

**Comment by Zero3K** [comment]
Then just fix the code if it breaks.

**Comment by TheDurtch** [comment]
I am pretty sure @SahilAgarwal321 mean that "unchainedTorrent" might be so baked in to the code it would take a full rewrite to change it.

**Comment by Zero3K** [comment]
It didn't look that way to me when I did a search through the code.

**Comment by SahilAgarwal321** [comment]
I am pretty sure @SahilAgarwal321 mean that "unchainedTorrent" might be so baked in to the code it would take a full rewrite to change it.

Yep. This is a django application that was created initially when the whole project was started. There are literally around 10-15 places where changes are needed to be done to rename a django application.

**Comment by Zero3K** [comment]
Does that mean it won't be changed?

**Comment by SahilAgarwal321** [comment]
Yep.

**Comment by Zero3K** [comment]
Okay.
