### ISSUE TITLE
Display filename of fopnu URL

### ISSUE THREAD

**Issue by Zero3K** [Zero3K/nulinks#2]
It would be nice if it would show the filename/chat room name associated with the fopnu URL instead of the entire link.

**Comment by SahilAgarwal321** [comment]
Could you give an example??

**Comment by Zero3K** [comment]
fopnu:chat:l76nkuzeszrr6vg7uo6cwxlk3q64lsuonixlfuc4bjzshxkos77a/FopnuUserGroup%20-%20Help%20%26%20Support (The chat room name is after the / which is after the hash used when connecting to it. The same also applies for file links).

**Comment by TheDurtch** [comment]
`fopnu:chat:l76nkuzeszrr6vg7uo6cwxlk3q64lsuonixlfuc4bjzshxkos77a/FopnuUserGroup%20-%20Help%20%26%20Support` should appear as `Chat: FopnuUserGroup Help - And Support`
I think all chat room or links that start with fopnu:chat: should have there entry start with `Chat: `
and
`fopnu:file:rnevrqcaiyhmy527g5djwkxafjmpvzuooi3tbyiirvm7eit3675aaacad4aaaaaa/test-file` should appear as `test-file`

**Comment by Zero3K** [comment]
A user of Fopnu has made some changes to it in regards to this issue. I am attaching the archive so that they can be integrated.

[unchained-torrent.zip](https://github.com/Zero3K/nulinks/files/2994002/unchained-torrent.zip)

**Comment by SahilAgarwal321** [comment]
What is the change??

**Comment by Zero3K** [comment]
Do you want the files that were changed or to know what changes he made to them?

**Comment by SahilAgarwal321** [comment]
Both would be good.

**Comment by Zero3K** [comment]
You don't trust his work? All you need to do is extract the archive I attached and look through it to see what changed.

**Comment by Zero3K** [comment]
Any news?

**Comment by SahilAgarwal321** [comment]
Its not about trust. I dont know where the changes are in the code. I need at least the filenames of what to look at. There are many ways this thing can be implemented, I dont know which way he did it. It'll be easier to understand if I knew where to look.

**Comment by Zero3K** [comment]
Here's a screenshot that lists the files (the ones with the date of March 21st are the ones to look at):

![Modified Files #1](https://user-images.githubusercontent.com/6194332/54883565-1394c800-4e3d-11e9-9f17-fdac0faf10fa.png)

**Comment by SahilAgarwal321** [comment]
Umm can you just point me to where you got the code from? Provide the link here?

**Comment by Zero3K** [comment]
https://github.com/Zero3K/nulinks/files/2994002/unchained-torrent.zip

**Comment by SahilAgarwal321** [comment]
Im sorry. I am unable to find exactly what he changed in the code. How did you find this zip file. Point me to the code from which you made this zip file.

**Comment by Zero3K** [comment]
I got it from him directly via Fopnu. The link to it is fopnu:user:sq5or7lofmgo3awgg75xusbtbajtvj2ntjvwiw3duux2fzycrjra/draco%2B%2B%20%28support%20LGBT%20rights%29/unchained-links/unchained-links-0.1.2/unchained-torrent

**Comment by Zero3K** [comment]
Still no luck?

**Comment by SahilAgarwal321** [comment]
No worries. I'm implementing it my way.

**Comment by Zero3K** [comment]
Thanks :smiley:

**Comment by Zero3K** [comment]
Will the Link column also be removed as part of this change?

**Comment by SahilAgarwal321** [comment]
Do you want to remove it? Merge link and name columns?

**Comment by Zero3K** [comment]
Yes, and make the Name link clickable (it should open the fopnu url associated to it in Fopnu).

**Comment by Zero3K** [comment]
Thanks for implementing it. By the way, there's no need for chat room links to be displayed as Chat: ROOM NAME. They should be displayed as ROOM NAME since categorization is now implemented (which means that all chat room links can be categorized as Chat Room).

**Comment by SahilAgarwal321** [comment]
> Thanks for implementing it. By the way, there's no need for chat room links to be displayed as Chat: ROOM NAME. They should be displayed as ROOM NAME since categorization is now implemented (which means that all chat room links can be categorized as Chat Room).

Okay.

Another thing. For the existing URLs we will have to run a script that will update the name field of all existing URLs.

```
import urllib

def get_name(url_location)
    if "fopnu" in url_location:
        if "chat:" in url_location:
            url_location_parsed = urllib.unquote(url_location)
            name = url_location_parsed.split("/")[-1]
        elif "file:" in url_location:
            url_location_parsed = urllib.unquote(url_location)
            name = "File: " + url_location_parsed.split("/")[-1]
        else:
            name = url_location
    else:
        name = url_location
    return name

from files.models import TorrentFile
torrent_files = TorrentFile.objects.all()
for i in torrent_files:
    i.name = get_name(i.location)
    i.save()
```

**Comment by Zero3K** [comment]
What do I change in order for it to show like how I mentioned?

**Comment by Zero3K** [comment]
Never mind. It has been implemented like how I mentioned. Thanks.
