### ISSUE TITLE
Remove the number of entries notification

### ISSUE THREAD

**Issue by Zero3K** [Zero3K/nulinks#21]
It would be nice if you did that since there is really no need for it.

**Comment by Zero3K** [comment]
Well?

**Comment by SahilAgarwal321** [comment]
Where is this exactly?

**Comment by Zero3K** [comment]
At the bottom of the page.

**Comment by SahilAgarwal321** [comment]
Oh I get what you are saying. Are you sure? I have found when there are too many rows. It helps immensely, specially as it gets updated when searching for records.

**Comment by Zero3K** [comment]
Never mind. How about limiting the number of entries shown and putting the rest in as many pages as needed?

**Comment by SahilAgarwal321** [comment]
Okay. 10 limit cool?

**Comment by Zero3K** [comment]
Either that or 50 would be fine.

**Comment by SahilAgarwal321** [comment]
Im assuming replied to my 20 limit stmt. Okay. Will do.

**Comment by Zero3K** [comment]
I don't see a page number list at the bottom of the list when there's more links than the ones currently being shown. Please implement one. Thanks.

**Comment by TheDurtch** [comment]
well there is only 2 pages so....

**Comment by Zero3K** [comment]
2 pages where?

**Comment by TheDurtch** [comment]
![image](https://user-images.githubusercontent.com/2914681/54958970-a1e47900-4f25-11e9-8740-78e0bf8a1783.png)
