### ISSUE TITLE
Update README screenshots

### ISSUE THREAD

**Issue by SahilAgarwal321** [Zero3K/nulinks#25]
As the title says

**Comment by TheDurtch** [comment]
I'll take care of this when I make link name changes

**Comment by Zero3K** [comment]
They haven't been updated yet.

**Comment by SahilAgarwal321** [comment]
Easy bro :D open source. Plus we all work. What's the hurry?

**Comment by TheDurtch** [comment]
yup some of us have **full time** jobs. that's why I only update the server right before I go to bed. ;)

**Comment by Zero3K** [comment]
I tried updating them but I cannot figure out how to size the browser window properly in order for the header and page number to show up and the font used by the site is blurred because of the resizing it is doing. Maybe someone else can try to make better screenshots than me.

**Comment by Zero3K** [comment]
@TheDurtch Thanks for taking better ones. I'll go ahead and close this issue now.

**Comment by TheDurtch** [comment]
I'll update them as major changes happen
