### ISSUE TITLE
List of wanted Categories

### ISSUE THREAD

**Issue by TheDurtch** [Zero3K/nulinks#27]
Please give me a list of wanted categories for me to add. Please when giving me this list separated them by newline,

**Comment by Zero3K** [comment]
Anime
Music
TV Shows
Movies
Books
Applications
Games
Pictures
Porn
Other
Chat Room

**Comment by Zero3K** [comment]
They should be sorted in alphabetical order.

**Comment by TheDurtch** [comment]
can't do that unless I redo all the categories unless @SahilAgarwal321 can do something in code.

**Comment by SahilAgarwal321** [comment]
I'll do that in the code.

**Comment by TheDurtch** [comment]
thanks

**Comment by SahilAgarwal321** [comment]
Where exactly do you want the alphabetical order to be?

**Comment by Zero3K** [comment]
The drop down list when choosing the category for the link that is to be posted.

**Comment by SahilAgarwal321** [comment]
Done
