### ISSUE TITLE
Blank tab showing when clicking on a Fopnu link

### ISSUE THREAD

**Issue by Zero3K** [Zero3K/nulinks#29]
It would be nice if that didn't happen. I noticed it happening in the latest version of Pale Moon.

**Comment by SahilAgarwal321** [comment]
I'll check it.

**Comment by Zero3K** [comment]
Is it fixable?

**Comment by SahilAgarwal321** [comment]
Could you elaborate more?

**Comment by Zero3K** [comment]
When I click on a link on the main page, an about:blank tab is made next to the tab containing nulinks.pw and then Fopnu starts downloading the link/connecting to the chat room.

**Comment by SahilAgarwal321** [comment]
Resolved.
