### ISSUE TITLE
Error when posting a fopnu link

### ISSUE THREAD

**Issue by Zero3K** [Zero3K/nulinks#30]
I'm getting an error when doing so. The error log is attached.

[AttributeError at _upload_.zip](https://github.com/Zero3K/nulinks/files/3006443/AttributeError.at._upload_.zip)

**Comment by SahilAgarwal321** [comment]
Could you just paste it here man? It's a hassle to check zip files.

**Comment by Zero3K** [comment]
Environment:


Request Method: POST
Request URL: http://nulinks.pw/upload/

Django Version: 1.11.20
Python Version: 3.6.8
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'files',
 'materialize']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback:

File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  23.                 return view_func(request, *args, **kwargs)

File "/home/kate/nulinks/files/views.py" in get_name
  45.                         url_location_parsed = urllib.unquote(url_location)

Exception Type: AttributeError at /upload/
Exception Value: module 'urllib' has no attribute 'unquote'

**Comment by SahilAgarwal321** [comment]
Okay. Guys are you ppl using python 3 or python 2 on the server??

**Comment by Zero3K** [comment]
Can't you tell by looking at location of the .py scripts contained in the log?

EDIT: Its 3.6.8.

**Comment by SahilAgarwal321** [comment]
Yeah. I'm just very surprised right now! I had been using python 2 and the code was still freaking working without any modifications! That's just something I didn't expect.

Anyways will fix it.

**Comment by Zero3K** [comment]
I hope that it is fixed soon so people can post links.

**Comment by Zero3K** [comment]
Any news? I know that you have a job but this issue should've been fixed a while ago since its keeping people away.

**Comment by SahilAgarwal321** [comment]
Done. Check and tell me if it works. Ill close it then.

**Comment by Zero3K** [comment]
I can confirm that it has been fixed.
