### ISSUE TITLE
Footer too big 

### ISSUE THREAD

**Issue by SahilAgarwal321** [Zero3K/nulinks#31]
I feel that the footer has gotten too big. It feels bloated on my laptop. Should we reduce some text??

**Comment by TheDurtch** [comment]
or make it not always on screen

**Comment by Zero3K** [comment]
I agree with hiding it until a user scrolls down to the end of the page.

**Comment by TheDurtch** [comment]
we could also merge lines 1 and 2 together looks ok on my 1600 x 900 screen 

![image](https://user-images.githubusercontent.com/2914681/55032643-5d1d1880-4fdf-11e9-9f9b-a3722465be56.png)

Code (edited using F12 on Chrome):
`<h6 class="text-center pt-2">Sharing is caring! These links are powered by the Fopnu P2P Network - <a target="_blank" href="https://www.fopnu.com">https://www.fopnu.com</a> | Nulinks v0.3 was made with Django 1.11.20 and Python 3.7.2 based on <a href="https://github.com/sksdlin/unchained-torrent" target="_blank"> Unchained Torrent</a></h6>`

**Comment by Zero3K** [comment]
That'll be fine.

**Comment by SahilAgarwal321** [comment]
Done
