### ISSUE TITLE
What is going on?

### ISSUE THREAD

**Issue by Zero3K** [Zero3K/nulinks#33]
*subject*

Its been a while since the last commit. I hope to see that change soon.

**Comment by Zero3K** [comment]
Thanks 😃

**Comment by SahilAgarwal321** [comment]
Heya guys! Signing out now. Will not be contributing much here form now on. Good luck!

**Comment by Zero3K** [comment]
Please fix the issues I recently posted soon. Thanks in advance.

**Comment by SahilAgarwal321** [comment]
Will not be able to help for a while man. Sorry.

**Comment by Zero3K** [comment]
That sucks. If only those issues were known about beforehand.

**Comment by Zero3K** [comment]
Any updates?

**Comment by Zero3K** [comment]
I hope to see more done on the site's code soon.

**Comment by Zero3K** [comment]
Any news?
