### ISSUE TITLE
Issue with the name of a fopnu link shown in the list

### ISSUE THREAD

**Issue by Zero3K** [Zero3K/nulinks#36]
It has the File: part included in its name when it shouldn't.

**Comment by Zero3K** [comment]
Another issue is that fopnu:user: links aren't showing up as the name of the directory that is being linked (such as fopnu:user:sqbmnf7qi4imfpwygumq6dmqdqqwmtmzy4ocd5uonjzulruohptq/Zero3K/Downloads/Rudora%20no%20Hihou%20OSV not being named Rudora no Hihou OSV).

**Comment by SahilAgarwal321** [comment]
Open a different issue for that.

**Comment by Zero3K** [comment]
Thanks for fixing it. I am going to close this issue.
