### ISSUE TITLE
fopnu:user: links should show as the directory name

### ISSUE THREAD

**Issue by Zero3K** [Zero3K/nulinks#37]
fopnu:user: links aren't showing up as the name of the directory that is being linked (such as fopnu:user:sqbmnf7qi4imfpwygumq6dmqdqqwmtmzy4ocd5uonjzulruohptq/Zero3K/Downloads/Rudora%20no%20Hihou%20OSV not being named Rudora no Hihou OSV).

**Comment by SahilAgarwal321** [comment]
What is it showing as? So I can find it.

**Comment by Zero3K** [comment]
fopnu:user:sqbmnf7qi4imfpwygumq6dmqdqqwmtmzy4ocd5uonjzulruohptq/Zero3K/Downlo...

**Comment by SahilAgarwal321** [comment]
You need to tell me if there are other kinds of links. I know three now (user is new) -

chat
file
user

**Comment by Zero3K** [comment]
That's all there is.

**Comment by Zero3K** [comment]
Thanks for implementing it. I am going to close this issue since it has been added.

**Comment by Zero3K** [comment]
I wonder if its possible to show "Rudora no Hihou OSV" instead of "/Zero3K/Downloads/Rudora no Hihou OSV". If so, please do that.
