### ISSUE TITLE
Improve the columns used in the front page

### ISSUE THREAD

**Issue by Zero3K** [Zero3K/nulinks#5]
They should be made wider in order to be able to fit the date and any long filenames in one line.

**Comment by SahilAgarwal321** [comment]
The filenames are waaay too long. How about truncating them?? If it exceeds say 80 characters, I'll display 80 charaacters + ... for the filename. When user goes to Load Link, they still get the file link.

**Comment by Zero3K** [comment]
I see that you applied the change that you mentioned. Thanks.
