### ISSUE TITLE
Needs Admin/Mod accounts

### ISSUE THREAD

**Issue by TheDurtch** [Zero3K/nulinks#7]
Needs Admin/Mod accounts for removing bad/illegal links such as CP.
I know someone is going to post some CP in here and I need a way to easily remove it.

**Comment by SahilAgarwal321** [comment]
I've created an admin site for it. Someone will have to create a superuser who can access the admin site. Who has access to the server on which this website is running?

**Comment by TheDurtch** [comment]
I do.

**Comment by SahilAgarwal321** [comment]
Cool. Create as superuser. I have created an admin panel. Check it out.

**Comment by TheDurtch** [comment]
Works great! Thanks
